  server:
    port: 8084
  mybatis:
    mapper-locations: classpath:mappers/*xml
    type-aliases-package: com.pra.project.pojo,com.pra.project.VO
    configuration:
      map-underscore-to-camel-case: true
  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      name: defaultDataSource
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: 226624lyr
    #servlet:
     # multipart:
      #  location: C:/Users/Administrator/Desktop/毕业设计项目/代码/project/pic/
    mvc:
      static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${spring.servlet.multipart.location}
